# vi:syntax=yaml
name: Build Image and Push to ECR
on:
  push:
    # You can set these branches to any that you want to build and push images from
    branches:
      - gds
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # Checks out the code from this repo
      - uses: actions/checkout@main

      # Builds a docker image from ./dockerfile, and pushes it to our ECR repository
      - uses: glg/build-and-push@main
        with:
          ecr_uri: ${{secrets.GLGAPP_ECR_URI}}
          access_key_id: ${{secrets.GLGAPP_ECR_AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{secrets.GLGAPP_ECR_AWS_SECRET_ACCESS_KEY}}
          healthcheck: ''
  build-and-push-arm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
        with:
          platforms: linux/arm64
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        with:
          install: true
          version: latest
      - uses: glg/build-and-push@main
        with:
          platform: linux/arm64
          ecr_uri: ${{secrets.GLGAPP_ECR_URI}}
          access_key_id: ${{secrets.GLGAPP_ECR_AWS_ACCESS_KEY_ID}}
          secret_access_key: ${{secrets.GLGAPP_ECR_AWS_SECRET_ACCESS_KEY}}
          healthcheck: '/diagnostic'
          image_tag: arm64